### ISSUE TITLE
History permission? And: Folding comments/posts

### ISSUE THREAD

**Issue by josephrocca** [doublemarket/hnpopup#1]
Hi, neat extension! I was going to build something like this myself, but did a quick google search and stumbled across yours.

I'm wondering why it needs access to my browser history? It's better than [this one](https://chrome.google.com/webstore/detail/newsit-hacker-news-and-re/nngjdplpkehilhcinpccdbkjaknkkifl) which requires access to all website data (!), but it seems unnecessary given how it works?

Also, it would be great if I could "fold" and "unfold" comments with a little [+] and [-] buttons like on hackernews. And being able to do that for a whole post would be handy too.

**Comment by doublemarket** [comment]
@josephrocca Hello and thank you for the words!

Regarding the required permission, this extension needs to get the title and the URL of the page in tabs to show them in the popup and to get the point for the pages. The [tabs](https://developer.chrome.com/extensions/tabs) permission which shows "Read your browsing history" is required to get them:

> However, the "tabs" permission is required in order to populate the url, title, and favIconUrl properties of Tab.

I know using the [activeTab](https://developer.chrome.com/extensions/activeTab) permission is an option to narrow the access to data but I want the extension to show the point of a page instantly when opening the page, which the `activeTab` doesn't allow.

Hope this makes sense and please correct me if I miss something!

Also thanks for the suggestion! Folding/Unfolding comments is a good feature to have so I'm leaving this issue opened until the feature is implemented.

**Comment by doublemarket** [comment]
@josephrocca I've added the fold/unfold comments feature to the latest `v0.4`. The update is now available so please try it out!

**Comment by josephrocca** [comment]
Neat! Cheers. One slightly annoying thing is that if I middle-click (or ctrl+click) a link in the extension's popup to open the link in a new tab, then the popup closes and I need to open it and scroll back down to where I was. I'm guessing this is just a limitation of popups though.

Thanks for the handy extension!

**Comment by doublemarket** [comment]
@josephrocca Yeah, I also want the popup keep opened but unfortunately it's [not possible](https://developer.chrome.com/extensions/faq#faq-persist-popups). Anyway thanks for the suggestion and also thanks for using 👍
